<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Kegiatan_magang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get kegiatan_magang by id_kegiatan
     */
    function get_kegiatan_magang($id_kegiatan)
    {
        return $this->db->get_where('tbl_kegiatan_magang', array('id_kegiatan' => $id_kegiatan))->row_array();
    }

    /*
     * Get all tbl_kegiatan_magang
     */
    function get_all_tbl_kegiatan_magang()
    {
        // $this->db->order_by('id_kegiatan', 'desc');
        // return $this->db->get('tbl_kegiatan_magang')->result_array();
        $this->db->select('*');
        $this->db->from('tbl_kegiatan_magang');
        $this->db->join('tbl_magang', 'tbl_kegiatan_magang.id_magang = tbl_magang.id_magang');
        $this->db->join('tbl_mhs_magang', 'tbl_magang.id_mhs = tbl_mhs_magang.id_mhs');
        return $this->db->get()->result_array();
    }
    function get_kegiatan_magang_mhs($id_magang)
    {
        // $this->db->order_by('id_kegiatan', 'desc');
        // return $this->db->get('tbl_kegiatan_magang')->result_array();
        $this->db->select('*');
        $this->db->from('tbl_kegiatan_magang');
        $this->db->join('tbl_magang', 'tbl_kegiatan_magang.id_magang = tbl_magang.id_magang');
        $this->db->join('tbl_mhs_magang', 'tbl_magang.id_mhs = tbl_mhs_magang.id_mhs');
        $this->db->where('tbl_magang.id_magang', $id_magang);
        return $this->db->get()->result_array();
    }
    function get_kegiatan_magang_pegawai($id)
    {
        // $this->db->order_by('id_kegiatan', 'desc');
        // return $this->db->get('tbl_kegiatan_magang')->result_array();
        $this->db->select('*');
        $this->db->from('tbl_kegiatan_magang');
        $this->db->join('tbl_magang', 'tbl_kegiatan_magang.id_magang = tbl_magang.id_magang');
        $this->db->join('tbl_mhs_magang', 'tbl_magang.id_mhs = tbl_mhs_magang.id_mhs');
        $this->db->join('tbl_pegawai', 'tbl_magang.kode_pegawai = tbl_pegawai.kode_pegawai');
        $this->db->where('tbl_pegawai.kode_pegawai', $id);
        return $this->db->get()->result_array();
    }

    /*
     * function to add new kegiatan_magang
     */
    function add_kegiatan_magang($params)
    {
        $this->db->insert('tbl_kegiatan_magang', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update kegiatan_magang
     */
    function update_kegiatan_magang($id_kegiatan, $params)
    {
        $this->db->where('id_kegiatan', $id_kegiatan);
        return $this->db->update('tbl_kegiatan_magang', $params);
    }

    /*
     * function to delete kegiatan_magang
     */
    function delete_kegiatan_magang($id_kegiatan)
    {
        return $this->db->delete('tbl_kegiatan_magang', array('id_kegiatan' => $id_kegiatan));
    }
}
